name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    uses: inveniosoftware/workflows/.github/workflows/pypi-publish.yml@master
    secrets: inherit
    with:
      babel-compile-catalog: true
